### PR TITLE
bump protobuf for RUSTSEC-2019-0003

### PR DESCRIPTION
**Pull request by PsiACE**
Just bump protobuf to 2.8, consistent with tikv, avoid RUSTSEC-2019-0003 

Signed-off-by: Chojan Shang <psiace@outlook.com>

### CODE REVIEW

**Review by kennytm — APPROVED** [review]

**Comment by BusyJay** [comment]
Isn't 2 includes "2.8" already?

**Comment by PsiACE** [comment]
> Isn't 2 includes "2.8" already?

But 2 also includes 2.7 and below

**Comment by BusyJay** [comment]
Yes, so dependents can upgrade to preferred versions at any time. As long as it doesn't depend on affected versions only, there is nothing to be done in a library.

**Comment by PsiACE** [comment]
But 2 does not guarantee that you will use version 2.8 and above

**Comment by BusyJay** [comment]
Cargo will guarantee latest version is used when possible. If a `Cargo.lock` is used, it's binary maintainer's responsibility to update the vulnerable dependencies.

**Comment by PsiACE** [comment]
> Cargo will guarantee latest version is used when possible. If a `Cargo.lock` is used, it's binary maintainer's responsibility to update the vulnerable dependencies.

ok

**Comment by kennytm** [comment]
> Cargo will guarantee latest version is used when possible.

Not really, Cargo has the (unstable) features [`-Z minimal-versions` and `-Z direct-minimal-versions` flags](https://doc.rust-lang.org/cargo/reference/unstable.html#minimal-versions) (rust-lang/cargo#5657) which the former allows the resolver to pick 2.0.0 rather than 2.8.x. 

Of course, at the end it is still the binary maintainer's (only they can add those 2 flags to affect the generated `Cargo.lock`) responsibility to pin protobuf to 2.8.

**Pull request closed without merging**
