### PR TITLE
Update to prost 0.11

### PR DESCRIPTION
**Pull request by agourlay**
This PR updates the project to prost 0.11 https://github.com/tokio-rs/prost/releases/tag/v0.11.0

### CODE REVIEW

**Comment by agourlay** [comment]
@BusyJay sorry to ping you directly but I cannot request a review through github's UI :)

I am trying to update the `prost` setup for `raft-rs` as it is preventing us from upgrading dependencies on our codebase.

**Comment by agourlay** [comment]
The build failed because 

> prost-build now requires protoc to be available in the path or set
via the PROTOC env var.

Installing `protobuf-compiler` should do the trick.

**Review by BusyJay — APPROVED** [review]

**Comment by agourlay** [comment]
Thanks a lot for the merge, WDYT about tagging 0.14.0?

**Comment by BusyJay** [comment]
Now it's published.

**Pull request merged**
