### PR TITLE
deps: Upgrade prost-build to 0.9

### PR DESCRIPTION
**Pull request by Xuanwo**
Signed-off-by: Xuanwo <github@xuanwo.io>

### CODE REVIEW

**Review by BusyJay — APPROVED** [review]

**Comment by sticnarf** [comment]
Do we also upgrade prost versions of tests?

**Comment by Xuanwo** [comment]
BTW, I think we need to remove the not working travis app.

**Review by sticnarf — APPROVED** [review]

**Comment by sticnarf** [comment]
> BTW, I think we need to remove the not working travis app.

Sorry, I don't have the permission for this. Perhaps @zhouqiang-cl can help?

**Review by kennytm — APPROVED** [review]

**Comment by BusyJay** [comment]
May need a PR to bump the version.

**Comment by sticnarf** [comment]
> May need a PR to bump the version.

The project is already in an unreleased version. Is it necessary to bump the version again?

**Comment by BusyJay** [comment]
It's necessary for raft-rs.

**Pull request merged**
